name: Hola mundo

on:
  workflow_dispatch: # ejecuci√≥n manual
  push:
    branches:
      - main
    paths:
      - 'BibliotecaAPI/**'
      - 'TestingBiblioteca/**'
      - '.github/workflows/hola-mundo.yml'
  pull_request:
    branches:
      - main

jobs:
  saludar:
    runs-on: ubuntu-latest
    steps:
      - name: Muestra mensaje hola mundo
        run: echo "Hola mundo, Uriel"

      - name: Checkout
        uses: actions/checkout@v4

      - name: Listar los archivos del repositorio
        run: |
          echo "El repositorio ${{ github.repository }} contiene los siguientes archivos:"
          tree
